### ISSUE TITLE
Error on example code

### ISSUE THREAD

**Issue by sethcohn** [pythad/selenium_extensions#48]
* Selenium extensions version: current, fresh install
* Python version: 3.6.5
* Operating System: MacOS 10.12 (Sierra)

### Description

Tried to run example code (as written, with minor change of chromedriver location to /usr/local/bin
Got error.

### What I Did
```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    bot.goto_google()
  File "test.py", line 14, in goto_google
    self.populate_text_field(searchbox_locator, 'query')
  File "/Users/scohn/.pyenv/versions/3.6.5/lib/python3.6/site-packages/selenium_extensions/core.py", line 211, in populate_text_field
    input_element.send_keys(text)
  File "/Users/scohn/.pyenv/versions/3.6.5/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 350, in send_keys
    'value': keys_to_typing(value)})
  File "/Users/scohn/.pyenv/versions/3.6.5/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 499, in _execute
    return self._parent.execute(command, params)
  File "/Users/scohn/.pyenv/versions/3.6.5/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/Users/scohn/.pyenv/versions/3.6.5/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: headless chrome=65.0.3325.181)
  (Driver info: chromedriver=2.33.506106 (8a06c39c4582fbfbab6966dbb1c38a9173bfb1a2),platform=Mac OS X 10.12.6 x86_64)
```

**Comment by sethcohn** [comment]
Never mind, turned out to be older version of Chromedrive causing the issue.  Works now.
