### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by valeriikundas** [pythad/selenium_extensions#53]
* Selenium extensions version: latest
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description
I tried to install
```
pip install selenium_extensions
```
but received error.

### What I Did

I received this output:
```
Collecting selenium_extensions
  Using cached https://files.pythonhosted.org/packages/04/f8/6ae352eb71fc7c86601d1de25d9f385100801c9dfa1a1a8cda3d3f69ce06/selenium_extensions-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1w8z4fzq/selenium-extensions/setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------

Error:  An error occurred while installing selenium_extensions!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-1w8z4fzq/selenium-extensions/

This is likely caused by a bug in selenium_extensions. Report this to its maintainers.
```

**Comment by valeriikundas** [comment]
This error is caused because I use pip 10.0.1 and provided installation only works for pip<=9.0.3

**Comment by abject18** [comment]
> This error is caused because I use pip 10.0.1 and provided installation only works for pip<=9.0.3

Also happens with Python 3.8.3 and pip 20.1.1.

@valeriykundas  - Did you solve this? How?

**Comment by valeriikundas** [comment]
nope. it only works for pip<=9.0.3
